### ISSUE TITLE
Pretrained Model Not Found!

### ISSUE THREAD

**Issue by SonPH088** [ramgendeploy/headswap-machine#1]
Hi Ramgen,
Thanks for your hard work.

I'm very new in this field.
I would like to test your code, but the pretrained model path not found: 

pretrained_W = "/home/rama/legendfacesPipeline/models/bisenet_pretrained.pth"

Where can I download this model or which models can I use the same with "bisenet_pretrained.pth"?

Thanks!

**Comment by ramgendeploy** [comment]
Hey,
Sorry for the messy code, it needs more docs. 

I updated the files that had absolute paths, 
if you have a problem with the relative paths, change the paths to absolute from your local repo.
All the models are in the models folder in the repo.

I will do a video in the future, you can read this blogpost if you want more info: https://ramagg.com/headswap-pipeline/
If you have any trouble running the code, rise another issue or msj me on twitter @ramgendeploy

**Comment by SonPH088** [comment]
Hi Ramgen, 

I have found all the models and successfully run the code.
I need more time to learn how it works. 

Thanks for your help and have a nice day.
