### ISSUE TITLE
"test_result.jpg" is showing dark face

### ISSUE THREAD

**Issue by chetancc** [ramgendeploy/headswap-machine#3]
Hi Ramgen,
Thanks for your hard work.

I'm very new in this field.
I don't wanted to open new issue but didn't find right way to contact you. By the way I have followed you on twitter just now. I tried your code and found that "test_result.jpg" is showing dark face where as "source_1.jpg" is on fair side. Let me know if something needs to be changed. Attaching all files for your reference.

![headless_template](https://user-images.githubusercontent.com/17129451/139873914-fb3ad126-ce9c-472c-9421-98a7457de5b4.jpg)
![source_1](https://user-images.githubusercontent.com/17129451/139873933-81afe418-4f15-4745-a12f-a81d76f1ca9e.jpg)
![target_img](https://user-images.githubusercontent.com/17129451/139873949-de8e8ac6-30c3-4e81-9ee4-dcba0f1b9c0d.jpg)
![test_result](https://user-images.githubusercontent.com/17129451/139873968-4ceb2414-2c96-40a7-9665-2cec0b94a678.jpg)

**Comment by ramgendeploy** [comment]
Hi Chetancc, Thanks!

So here the pipeline has a style transfer mode for when you are swapping with paintings or drawings.
Currently in the lib, there is no option to remove this, I need to add this in an update.

But you can use this colab where I have the same pipeline but you can skip the style part:
https://colab.research.google.com/drive/1o3C92DuLKe92g6usNRiIS9jZbaWWKsNN?usp=sharing

**Comment by mirfan899** [comment]
any update on this?

**Comment by ramgendeploy** [comment]
Hi, as I said in the last comment you can use the colab version to get the output without the style.
